%YAML:1.0

#camera calibration
model_type: PINHOLE
camera_name: camera

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 1

#optimization parameters
max_solver_time: 0.14  # max solver itration time (ms), to guarantee real time 0.04
max_num_iterations: 10   # max solver itrations, to guarantee real time 8
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

fast_relocalization: 1

#loop closure
#if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
#also give the camera calibration file same as feature_tracker node
loop_closure_params:
    enable: 0
    min_correspondences: 0  #25
    pnp_reprojection_threshold: 0.0    #8

health:
    enable: 0
    min_keypoints: 15
    consecutive_keyframes: 3
    keyframe_wait_time: 2.0
    kps_per_quadrant: 1

debug_image: 1

image_height: 540
image_width: 960
focal_length: [711.2894861341305, 712.7030517816934]
principal_point: [489.1416953624786, 281.2222934237387]
distortion_coefficients: [0.3999119739097554, 0.3122915057539037, 0.005095664377546421, 0.004507000883126362]