%YAML:1.0
cameras:
    - {T_SC:
#         [ 0.01243228, -0.01734065,  0.99977234,  0.01287136,
#           -0.99985051,  0.01180011,  0.01263792,  0.02380705,
#           -0.01201658, -0.99978001, -0.01719136, -0.00774372,
#           0,          0,          0,          1], # zed2 imu
         [ -0.01398562, -0.04130217,  0.99904881,  0.14125295,
           -0.99988526,  0.0063937,  -0.01373301,  0.04480593,
           -0.00582042, -0.99912624, -0.04138685, -0.04005097,
           0,          0,          0,          1], #xsens imu
       image_dimension: [960, 540],
       distortion_coefficients: [0.3999119739097554, 0.3122915057539037, 0.005095664377546421, 0.004507000883126362],
       distortion_type: radialtangential,
       focal_length: [711.2894861341305, 712.7030517816934],
       principal_point: [489.1416953624786, 281.2222934237387]}

    - {T_SC:
#         [ 0.0116139,  -0.01632971,  0.99979921,  0.01494434,
#           -0.99986954,  0.01103535,  0.01179496, -0.09578688,
#           -0.01122574, -0.99980576, -0.01619942, -0.00911559,
#           0,          0,          0,         1], #zed2 imu
         [ -0.01478477, -0.04031248,  0.99907773,  0.14016725,
           -0.99987815,  0.00560251, -0.01457056, -0.07480717,
           -0.00500996, -0.99917141, -0.0403904,  -0.04069586,
            0,         0,          0,          1], #xsense
       image_dimension: [960, 540],
       distortion_coefficients: [0.3927122565501996, 0.31779433019998765, 0.003627300519256686, 0.004857738533935006],
       distortion_type: radialtangential,
       focal_length: [711.9057670969258, 712.8112892089378],
       principal_point: [489.67060072497924, 280.28861778176287]}

camera_params:
    camera_rate: 12
    sigma_absolute_translation: 0.0
    sigma_absolute_orientation: 0.0
    sigma_c_relative_translation: 0.0 # below 1.0e-6 ruines numerics...
    sigma_c_relative_orientation: 0.0 # below 1.0e-6 ruines numerics...

imu_params:
    a_max: 176.0 # acceleration saturation [m/s^2]
    g_max: 7.8 # gyro saturation [rad/s]
    #zed2 imu
#    sigma_g_c: 0.0014055528185900714 # gyro noise density [rad/s/sqrt(Hz)] 0.00016017
#    sigma_a_c: 0.009966421716092395 # accelerometer noise density [m/s^2/sqrt(Hz)] 0.00071376
#    sigma_bg: 5.153835140090435e-06 # gyro bias prior [rad/s]
#    sigma_ba: 0.000458035161786157 # accelerometer bias prior [m/s^2]
#    sigma_gw_c: 5.153835140090435e-06 # gyro drift noise density [rad/s^s/sqrt(Hz)] 0.00000165
#    sigma_aw_c: 0.000458035161786157 # accelerometer drift noise density [m/s^2/sqrt(Hz)] 0.00002874
    #xsens imu
    sigma_g_c: 0.0016210361526331097 # gyro noise density [rad/s/sqrt(Hz)] 0.00016017
    sigma_a_c: 0.005617343328024146 # accelerometer noise density [m/s^2/sqrt(Hz)] 0.00071376
    sigma_bg: 4.2781957524004126e-05 # gyro bias prior [rad/s]
    sigma_ba: 0.00014537747959689836 # accelerometer bias prior [m/s^2]
    sigma_gw_c: 4.2781957524004126e-05 # gyro drift noise density [rad/s^s/sqrt(Hz)] 0.00000165
    sigma_aw_c: 0.00014537747959689836 # accelerometer drift noise density [m/s^2/sqrt(Hz)] 0.00002874
    tau: 3600.0 # reversion time constant, currently not in use [s]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    a0: [ 0.0, 0.0, 0.0 ] # Accelerometer bias [m/s^2]
    imu_rate: 100
    # tranform Body-Sensor (IMU)
    T_BS:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, -1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, -1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]
sonar_params:
    T_SSo:
#        [-0.0907363, -0.0521933,   0.994506,   0.203479,
#         -0.995553,  0.0301427, -0.0892499,  0.0326268,
#         -0.0253189,  -0.998182, -0.0546962,  0.0188909,
#          0,          0,          0,          1]  # sonar to zed2 imu
        [-0.117299, -0.0756147,   0.990214,   0.332616,
         -0.992957,  0.0256546,  -0.115665,   0.048771,
         -0.0166576,  -0.996807, -0.0780914, -0.0180802,
          0,          0,          0,          1] # sonar to xsens imu

# Estimator parameters
numKeyframes: 5 # number of keyframes in optimisation window   5
numImuFrames: 3 # number of frames linked by most recent nonlinear IMU error terms  3

# ceres optimization options
ceres_options:
    minIterations: 3   # minimum number of iterations always performed
    maxIterations: 25  # never do more than these, even if not converged  20
    timeLimit: 0.135  # [s] negative values will set the an unlimited time limit 0.035

# detection
detection_options:
    threshold: 10.0      # detection threshold. By default the uniformity radius in pixels
    octaves: 1           # number of octaves for detection. 0 means single-scale at highest resolution
    maxNoKeypoints: 400  # restrict to a maximum of this many keypoints per image (strongest ones)

# delay of images [s]:
imageDelay: 0.0  # in case you are using a custom setup, you will have to calibrate this. 0 for the VISensor.

# display debug images?
displayImages: true  # displays debug video and keyframe matches. May be slow.
publishDebugImages: false  # publish debug image to topic ~debug_image_x

# use direct driver
useDriver: false

# some options for how and what to publish -- optional in ROS-free version
publishing_options:
    publish_rate: 100                  # rate at which odometry updates are published only works properly if imu_rate/publish_rate is an integer!!
    publishLandmarks: true             # select, if you want to publish landmarks at all
    landmarkQualityThreshold: 1.0e-2   # landmark with lower quality will not be published
    maximumLandmarkQuality: 0.05       # landmark with higher quality will be published with the maximum colour intensity
    maxPathLength: 20                  # maximum length of the published path
    publishImuPropagatedState: true    # Should the state that is propagated with IMU messages be published? Or just the optimized ones?
    # provide custom World frame Wc
    T_Wc_W:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]
    trackedBodyFrame: B                # B or S, the frame of reference that will be expressed relative to the selected worldFrame
    velocitiesFrame: Wc                # Wc, B or S,  the frames in which the velocities of the selected trackedBodyFrame will be expressed in

#Sharmin
isSonarUsed: false
isDepthUsed: false
isForwardSonarUsed: true
isRelocalization: true
histogramMethod: "CLAHE" # NONE, HISTOGRAM, CLAHE
#claheClipLimit: 3
#claheTileGridSize: 5
resizeFactor: 1  # by default 1.0. set this value if you want to resize the original image by this factor. You DO NOT need to change camera/projection matrix, those will be updated accordingly.